### PR TITLE
Template stream

### PR DESCRIPTION
**Pull request by gagern**
Sometimes it would be nice to use gulp streams for template input as well. This quite extensive patch does that. Let me know whether you'd feel comfortable including this kind of patch and remain the package maintainer. Or if this is too much change for your taste, whether you would be willing to transfer the package to me.

### CODE REVIEW

**Comment by philmander** [comment]
This is great!

Would you mind tweaking something slightly? I still need to run gulp-hbs in some Node 0.10 environments for now. It would be nice to pick up this update, but the combination of `'use strict'` and `const` keywords are failing in Node 0.10. Could you replace the `const`s with `var`s?

**Comment by gagern** [comment]
Sure, I can tweak this later today or tomorrow. And it's good to know that 0.10 compatibility is still relevant. I intend to clean up some things by using promises, and in that case I'll use a library like Q instead of relying on ES6 promises. I can also add 0.10 to the Travis configuration, to run the tests in that setup, too.

**Comment by philmander** [comment]
Maybe checkout Bluebird for promises

**Comment by gagern** [comment]
I don't really care what Promise implementation to use, as long as it can model Deferred. If you want [Bluebird](http://bluebirdjs.com/), that's what you get. I think the code is a lot cleaner now using these concepts, as we can now use a Deferred to indicate some template which on the one side may be resolved or rejected from the template stream processing, and on the other hand is being used by the input stream processing.

As I included Travis configuration (and verified that the new and quite extensive test suite [succeeds](https://travis-ci.org/gagern/gulp-hbs/builds/95304672) on Node 0.10), you might want to enable [Travis CI](https://travis-ci.org/) for the original project as well.

Note that I also extended the functionality quite a bit since I first posted this pull request. You might want to start with the [README](https://github.com/gagern/gulp-hbs/blob/templateStream/README.md) to see what functionality I'm aiming for.

**Comment by gagern** [comment]
What's the status here? Any chances of getting my changes in, or should I start this as a separate npm module?

**Comment by philmander** [comment]
Hi Martin, I've now merged your changes and published v0.2.0 to NPM

Thanks for the great updates and a have a happy christmas

**Pull request merged**
